### ISSUE TITLE
Would you like to install @types/react?

### ISSUE THREAD

**Issue by makhataibar** [nrwl/nx-labs#73]
After migrated to @nrwl/expo@14.2.3 can't start expo project.
<img width="1277" alt="Снимок экрана 2022-06-13 в 11 59 54" src="https://user-images.githubusercontent.com/27006656/173289930-89951a09-fb89-4033-94a3-f7356a61eb34.png">

I was try use every method of solve this problems, but I have still errors

**Comment by xiongemi** [comment]
i think you might have to downgrade @types/react: `"@types/react": "^17.0.45"`

**Comment by makhataibar** [comment]
@xiongemi but it's not compatible with latest nx migrations
I was try use` { "resolution": { "@types/react": "^17.0.45" } } `but it's not work

**Comment by jaysoo** [comment]
This is an issue with expo (it is trying to resolve `@types/react/index.dts`, which isn't a valid entry point in the new version). I've created a PR for it here https://github.com/expo/expo/pull/17880

Closing this for now since there's nothing we can do on our end. 

Users running into this may want to downgrade `@types/react` to v17 for now if you want to remove the warning.

**Comment by makhataibar** [comment]
@jaysoo https://github.com/expo/expo/pull/17911 they was merge changes like yours. I'm wait when expo-cli will update with this changes and @nrwl/expo up to new expo-cli version.
thanks
