### ISSUE TITLE
Utilize nx React library in Remix app

### ISSUE THREAD

**Issue by erichardson30** [nrwl/nx-labs#8]
I'm very intrigued by Remix and want to start building out an application with it. Currently our repo is set up with Nx and consists of a graphql api, react UI library, and a React front end. For the sake of this...let's say the name of our project is `example-project` and everything is scoped `@example-project`. 
Currently in the React front end, I can pull in a component like
`import {Checkbox} from '@example-projejct/ui';`

However, after using the nrwl remix app generator...when I try to import the checkbox the same way I get `Cannot find module '@example-project/ui' or its corresponding declarations.`

I tried adding to my remix package.json:
`"@example-project": "libs/ui"`
but that doesn't seem to make a difference.

Is there a way to get this to work?

**Comment by erichardson30** [comment]
And for a little more clarity here...
the react ui library I created...it is set to `buildable` so the build is getting generated to `dist/libs/ui`

in the package.json for my remix app, I added in:
`"@example-project/ui": "dist/libs/ui"`

and still no luck

**Comment by juristr** [comment]
Hey, thanks for reaching out. Note that the Remix plugin, for now, is still in labs, so there might totally be these rough edges still 😅 .

In order to provide a similar experience as with plain React workspaces or Next, we'd need some modifications within Remix that allows to link to local libraries more easily. Right now Remix considers itself being the root of the workspace (have a look at their tsconfig and package.json).

What the Nx Remix plugin does right now to work around it, is to setup a npm/yarn workspace. If you look into the package.json, you should see something like

```
{
   ...
   "workspaces": [
      "libs/*"
   ]
```

That means the npm/yarn workspace points to the libs folder. As such, we also need to have the compiled output of the buildable library in there. This is what the Remix Nx library generator does:

https://github.com/nrwl/nx-labs/blob/deb4e58a5b09e1bfa50e22fe2444a2f062e9a19b/packages/remix/src/generators/library/library.impl.ts#L43-L50

That said, you can adjust your React lib's output to also point to their local dist (in the workspace.json/project.json). That should make it work. Most probably you'll have to also run "npm install" / "yarn install" to have it registered with the npm/yarn workspace.

As you can see, it is not yet ideal in terms of DX as it has a couple of downsides, but it should work for now. And it would also be what you'd do with other monorepo tools. We hope we can improve it in the future, working together with the Remix team to get to a DX that is equivalent if not better to the current Next & React support in Nx :)

Hope this helps. Thanks for testing this in such an early stage & feel free to send feedback, we love to hear it and it'll help improve the support :)

**Comment by lodisy** [comment]
Hello, I noticed that it generates the module css bounded to the component. 

In my case, I am splitting the style into another lib called @xxx/themes, which utilizes `stitches` (another css in js library) for global and also component scoped styling. 

In such case, how can I make it work with Remix applications, for example global styling? I have solely imported the stitches config into the app, and made some modifications like [this](https://gist.github.com/jjenzz/b67c8bd263bbf0f4e39c5fca55db93ee). But Remix keeps not finding the module.

**Comment by asherccohen** [comment]
Hi @juristr, thanks for your answer.
I'm ina similar situation, testing out the remix plugin and trying to import a lib.

My understanding is that remix needs the built artifacts, so the generator tries to create a bundle and move it locally to the libs/myLib,/dist folder, is that right?

Then you mention

"That said, you can adjust your React lib's output to also point to their local dist (in the workspace.json/project.json). That should make it work. Most probably you'll have to also run "npm install" / "yarn install" to have it registered with the npm/yarn workspace"

Could you elaborate on this part because I'm not sure I'm following.

Thanks!
